apiVersion: appstudio.redhat.com/v1alpha1
kind: ApplicationSnapshot
metadata:
  name: m5-snapshot
  namespace: demo
spec:
  application: m5-application
  images:
    - component: applicationservice
      #      pullSpec: quay.io/hacbs-release-tests/build-artifact-1@sha256:4ff3ca91275773af45cb4b0834e12b7eb47d1c18f770a0b151381cd227f4c253
      pullSpec: quay.io/redhat-appstudio/user-workload@sha256:a098c342082fc7339cdbeee512c9d79cc2e216484552bdb773a8365d323d1d46
    - component: component-2
      pullSpec: quay.io/hacbs-release-tests/build-artifact-2@sha256:aa6c2c047467afc828e77e306041b7fa4a65734fe3449a54aa9c280822b0d87d
